### ISSUE TITLE
RLS server could not be connected

### ISSUE THREAD

**Issue by berkus** [tomv564/LSP#121]
Hi, after recent LSP update Rust RLS stopped working:

```
LSP: Config added: clangd (enabled)
LSP: Config added: jsts (enabled)
LSP: Config added: ocaml (enabled)
LSP: Config added: golsp (enabled)
LSP: Config added: reason (enabled)
LSP: Config added: dotty (enabled)
LSP: Config added: pyls (enabled)
LSP: Config added: rls (enabled)
environment variables loaded using: /usr/local/bin/fish -l

LSP: no clients found for window 8
LSP: no clients found for window 8
LSP: starting in /Users/berkus/Hobby/carma
LSP: starting ['rustup', 'run', 'nightly', 'rls']
LSP: request 1: initialize 
LSP: client registered for window 8 {'rls': <LSP.main.Client object at 0x1119844d0>}
LSP: got json:  {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".",":"]},"definitionProvider":true,"refer
LSP: notify: initialized
LSP: LSP stderr process ended.
LSP: notify: textDocument/didOpen
LSP: client unexpectedly died: [Errno 32] Broken pipe
LSP: LSP stdout process ended.

>>> from os import environ
>>> print(environ['PATH'])
/usr/local/sbin:/usr/local/bin:/Users/berkus/.cargo/bin:/Users/berkus/Tools/go/bin:/Users/berkus/Tools/bin:/Users/berkus/.gem/ruby/2.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
LSP: checking for clients on on  /Users/berkus/Hobby/carma
LSP: notify: textDocument/didChange
LSP: client unexpectedly died: [Errno 32] Broken pipe
LSP: notify: textDocument/didChange
LSP: client unexpectedly died: [Errno 32] Broken pipe
LSP: request 2: textDocument/completion 
LSP: client unexpectedly died: [Errno 32] Broken pipe
```

So RLS could be started but then crashes or otherwise ends, nothing interesting in the logs to that extent.
Running `rustup run nightly rls` from the command line seems to start the server at least.

**Comment by tomv564** [comment]
Hi Berkus, there was a discussion in the RLS repo here about a crash in the server when LSP sends the `initialized` notification: https://github.com/rust-lang-nursery/rls/issues/214

It looks like the RLS fix was merged, but I also made a preventative fix to LSP.

If it takes a while for the RLS fix to reach you, you could install the LSP package from master (see https://packagecontrol.io/docs/usage).

**Comment by berkus** [comment]
Thanks, I will check if nightly rls is updated today.

**Comment by golddranks** [comment]
Sadly, the RLS on Rust nightly is seldom updated. Of course, one can build RLS from source and `cargo install` it.

If it continues crashing, it would help to set the `RUST_LOG` env var to `rls=trace`, to get a better picture what is it doing and why does it crash. But it's likely to be fixed on the master of `RLS`, because a recent change made the parsing a lot more lenient.

**Comment by berkus** [comment]
Ok, i followed the instructions and updated LSP to the master build - it seems to work more stable now, although some completions are still missing, trying to figure out what's up with that.

**Comment by tomv564** [comment]
Going to close this issue now, LSP is still continually improving completions behaviour. Please open a new issue if you can narrow down a problem with RLS!
