### ISSUE TITLE
Selecting particular signature for overloaded functions

### ISSUE THREAD

**Issue by boyceg** [tomv564/LSP#683]
* OS and language server: MacOS / ccls
* How you installed LSP (Package Control or from git?): git

Requesting a feature? I am not sure

Thanks for all of your work on LSP for Sublime Text!

I am trying to use LSP+ccls on MacOS for C++ development.

For overloaded functions, the initial list of functions includes the function names but without signatures. For overloaded functions, there is a further list that appears for me once the function name includes parentheses. This secondary pop-up allows me to browse the available signatures, e.g. "1 of 6 overloads (use the "up" "down" keys to navigate): ...". However, once I get to this menu, I seem to be unable to select a particular signature, just to see what signatures are available.

This feels like a very dumb question... but: I was wondering if there was a way to see the function signature in the initial completion list (e.g., before selecting a particular one), and/or to change the selection once the arguments are initially filled in.

**Comment by rwols** [comment]
> I was wondering if there was a way to see the function signature in the initial completion list (e.g., before selecting a particular one)

The decision to show function parameters is up to the language server. We just display the server's completion items.

>  change the selection once the arguments are initially filled in.

Not sure what you mean. Is ccls pre-filling all arguments of a functions with a snippet? I haven't used that language server in a while.

> However, once I get to this menu, I seem to be unable to select a particular signature, just to see what signatures are available.

The language server protocol mostly mirrors how Visual Studio works. In Visual Studio you also cannot "select" a particular overload, you have to type out each argument separately.

Since you're on a Mac you've probably used Xcode. From what I can remember Xcode works a bit differently in that it shows *all* overloads in the initial completion widget and then once you "select" a completion it pre-fills the function with a snippet. There is no "signature help" widget in Xcode if I recall correctly.

**Comment by boyceg** [comment]
> > I was wondering if there was a way to see the function signature in the initial completion list (e.g., before selecting a particular one)
> 
> The decision to show function parameters is up to the language server. We just display the server's completion items.

With ccls I see two different completion lists. The first list, which shows up while still typing, lists all of the overloaded function names that match the pattern, but it does not provide any additional information about the actual signatures for the overloaded functions. It seems like once ccls figures out which of the overloaded functions has been selected, LSP will pre-fill the argument list for that particular overloaded function. However, it is sort of luck which function you get, and so if you guess "wrong", you have to go back and delete the pre-filled argument list.

Once the function has been identified, it becomes possible to scroll up/down to see the various function signatures that are available, but at this point the pre-filled argument list from the initial selection seems to be "baked in".

> > change the selection once the arguments are initially filled in.
> 
> Not sure what you mean. Is ccls pre-filling all arguments of a functions with a snippet? I haven't used that language server in a while.

I am not sure that I am doing a good job of describing the behavior, but yes, it will pre-fill based on the signature of the selected overloaded function. However there does not seem to be information available until after the selection is made/the snippet is pre-filled, to find out what the actual signature is.

> > However, once I get to this menu, I seem to be unable to select a particular signature, just to see what signatures are available.
> 
> The language server protocol mostly mirrors how Visual Studio works. In Visual Studio you also cannot "select" a particular overload, you have to type out each argument separately.
> 
> Since you're on a Mac you've probably used Xcode. From what I can remember Xcode works a bit differently in that it shows _all_ overloads in the initial completion widget and then once you "select" a completion it pre-fills the function with a snippet. There is no "signature help" widget in Xcode if I recall correctly.

I have been using EasyClangComplete, which presents a list of available overloaded functions with their arguments and then pre-fills snippets corresponding to the particular signature that is suggested.

I wonder if clangd would behave differently. I am using ccls because Homebrew's clangd was having trouble finding standard system headers, and because I was getting weird permission denied errors when trying to use clangd in the location where brew installs it. I may give clangd another try --- I think I know how to get it to work by adding some extra preprocessor directives in the compile_commands.json file.

**Comment by rwols** [comment]
With clangd, you may use `-completion-style=detailed`. It should display all overloads in ST's completion widget. The default is `-completion-style=bundled`.

**Comment by boyceg** [comment]
That sounds like what I am looking for. I will give clangd another try later this week, and see if I can find comparable flags for ccls.

**Comment by rwols** [comment]
By the way, about the missing headers on macOS: I think I ran into this too before, and documented how to set up LLVM. Running this in the terminal should fix the missing header problems:

```sh
# This used to be sufficient
xcode-select --install
# But since 10.14 this is necessary too
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

**Comment by boyceg** [comment]
> With clangd, you may use `-completion-style=detailed`. It should display all overloads in ST's completion widget. The default is `-completion-style=bundled`.

At least with clangd 8.0.1, I do not see any difference in the completions for the two different completion styles. The completion widget shows the return type of the function, but not the arguments. FWIW, my project settings look like:
```
	"settings":
	{
		// ...
		"LSP":
		{
			"clangd":
			{
				"command":
				[
					"/usr/local/bin/clangd",
					"-completion-style=detailed"
				],
				"enabled": true,
			}
		},
		// ...
	}    
```

**Comment by tomv564** [comment]
The settings look good, especially if you can see the extra argument being logged to Sublime's console when it starts clangd. 

Interesting thought, letting SignatureHelp update an inserted snippet if the user selects an overload. I wonder if VS Code handles this?

Anyways, please close the issue if it is solved with configuring the language server.

**Comment by boyceg** [comment]
Unfortunately, I don't see any difference in LSP when running with/without `clangd -completion-style=detailed` --- adding the extra configuration flag does not appear to solve this issue.

It sounds like LSP will use whatever is being provided by `clangd`/`ccls` --- is there some way for me to see what is being provided, to see if these flags have any effect on the language server itself?

**Comment by tomv564** [comment]
Yes, there is a `log_payloads` setting under *Preferences: LSP Settings* which should write the response to completion requests to the Sublime console (see https://lsp.readthedocs.io/en/latest/troubleshooting/)

There is a chance that the Sublime Text completion UI sees two overloads with the same label and just combines them anyways.

**Comment by boyceg** [comment]
`log_payloads` indicates that `clangd` is reporting the full signature for each of the overloaded methods during completion.

**Comment by rwols** [comment]
Right, so you want to *also* set

```
	"prefer_label_over_filter_text": true,
```
together with `-completion-style=detailed` in your client config. This will show *all* overloads in ST's completion widget together with the signatures. And if you select one a snippet is inserted in the buffer that you can tab through.

Personally I prefer using `-completion-style=bundled` because that flows better with the signature help widget.

**Comment by rwols** [comment]
with `-completion-style=detailed`
<img width="1359" alt="Schermafbeelding 2019-08-26 om 23 49 04" src="https://user-images.githubusercontent.com/2431823/63726025-5af40a00-c85c-11e9-90af-bda2cb1709af.png">

with `-completion-style=bundled`
<img width="845" alt="Schermafbeelding 2019-08-26 om 23 49 57" src="https://user-images.githubusercontent.com/2431823/63726037-63e4db80-c85c-11e9-8bf0-af469fd8e08a.png">

**Comment by tomv564** [comment]
Any follow-up issues or documentation here? Otherwise, let's close :)
